// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs";

function intEqual(message, a, b) {
  Test.assertion(message, "Int equals", (function (a, b) {
          return a === b;
        }), a, b);
}

Test.test("add", (function () {
        intEqual(undefined, 2, 2);
        intEqual("1 + 2 === 3", 3, 3);
      }));

export {
  intEqual ,
}
/*  Not a pure module */
