// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function assertEqual(a, b, message) {
  Test.assertion(message, undefined, (function (a, b) {
          return a === b;
        }), a, b);
}

function MakeTerm(Term) {
  var termEquivalent = function (t1, t2, message) {
    Test.assertion(message, undefined, Term.equivalent, t1, t2);
  };
  var testParse = function (input, t2, message) {
    var res = Term.parse(input, [], Caml_option.some(Term.makeGen()));
    if (res.TAG !== "Ok") {
      return Test.fail("parse failed: " + res._0, undefined);
    }
    var res$1 = res._0;
    assertEqual(res$1[1], "", input + " input consumed");
    var message$1 = Core__Option.getOr(message, input + " equals expectation");
    termEquivalent(res$1[0], t2, message$1);
  };
  return {
          termEquivalent: termEquivalent,
          testParse: testParse
        };
}

export {
  assertEqual ,
  MakeTerm ,
}
/* Test Not a pure module */
